language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
before_script:
  - 'npm i -g gatsby-cli'
  - 'npm i'
deploy:
  provider: script
  script: npm run deploy
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
notifications:
  email:
    on_success: always
    on_failure: always
